users/urls.py
from django.urls import path

from .views import home_view, signup_view, dashboard_view,emailmsg,add_Code_view,auth,SignUpView

app_name = "users"

urlpatterns = [

    path('', home_view, name='home'),
   # path('signup/', signup_view, name='sign-up'),
    path('sign-up/', SignUpView.as_view(), name='sign-up'),

    path('dashboard/', dashboard_view, name='dashboard'),
    path('OTP/', auth, name='OTP'),
   # path('OTP/',add_Code_view.as_view(),name='OTP'),


   # path('OTP/', emailmsg("authentcations"," Your OTP is: ","ftcode2021@gmail.com"), name='OTP'),

    
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import  LogoutView
from users.views import LoginUser
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('profile/', include('profiles.urls', namespace='profiles')),
    path('file/', include("file_upload.urls")),
    path('file/', include("file_download.urls")),
]

urlpatterns += [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
 
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
	username = forms.CharField(
		label='',
		max_length=30,
		min_length=5,
		required=True,
		widget=forms.TextInput(
			attrs={
				"placeholder": "Username",
				"class": "form-control"
			}
		)
	)

	email = forms.EmailField(
		label='',
		max_length=255,
		required=True,
		widget=forms.EmailInput(
			attrs={
				"placeholder": "Email",
				"class": "form-control"
			}
		)
	)

	password1 = forms.CharField(
		label='',
		max_length=30,
		min_length=8,
		required=True,
		widget=forms.PasswordInput(
			attrs={
				"placeholder": "Password",
				"class": "form-control"
			}
		)
	)

	password2 = forms.CharField(
		label='',
		max_length=30,
		min_length=8,
		required=True,
		widget=forms.PasswordInput(
			attrs={
				"placeholder": "Confirm Password",
				"class": "form-control"
			}
		)
	)

	location = forms.CharField(
		label='',
		max_length=30,
		required=False,
		widget=forms.HiddenInput(
			attrs={
				"display": "none"
			}
		)
	)

	class Meta:
		model = User
		fields = ('username', 'email', 'password1', 'password2', 'location')

templates/app/dashboard.html
{% extends "auth\base.html" %}

{% block title %}
	Dashboard
{% endblock %}

{% block content %}

	{% if messages %}

	    {% for message in messages %}

		<!--Panel-->
		<div class="card border-success mb-3">
		    <div class="card-header text-danger">
		        <p class="card-title">{{ message }}</p>
		    </div>
		</div>
		<!--/.Panel-->
	    
	    {% endfor %}

	{% endif %}

	<h1 class="mt-5 text-center">Welcome {{ request.user }}</h1>
	<p class="text-left mt-5">Bio: {{ user.profile.bio }}</p>
	<p class="text-left">Joined: {{ user.profile.timestamp }}</p>

{% endblock content %}

templates/app/home.html
{% extends "auth\base.html" %}

{% block title %}
	Home
{% endblock %}

{% block content %}

	{{ block.super }}

{% endblock content %}

templates/app/profile_edit.html
{% extends "auth\base.html" %}
{% load widget_tweaks %}

{% block title %}
	Edit Bio
{% endblock %}

{% block content %}
	
	<div class="text-left mt-5 container">
		{% for field in form %}
		    <p>
	        	{{ field.label_tag }}
	        	{{ field|attr:"rows:20"|attr:"cols:20" }}
		        <!-- {% if field.help_text %}
		          <small style="color: grey">{{ field.help_text }}</small>
		        {% endif %} -->
		        {% for error in field.errors %}
		          <p style="color: red">{{ error }}</p>
		        {% endfor %}
		    </p>
		{% endfor %}
	</div>

{% endblock %}

templates/app/signup.html
{% extends "auth\base.html" %}

{% block title %}
	Sign Up
{% endblock %}

{% block content %}
	
	{% if messages %}

	    {% for message in messages %}

		<!--Panel-->
		<div class="card border-danger mb-3">
		    <div class="card-header text-danger">
		        <p class="card-title">{{ message }}</p>
		    </div>
		</div>
		<!--/.Panel-->
	    
	    {% endfor %}

	{% endif %}

<div class="login-wrap">


	<div class="login-html">
		<!-- Default form register -->
		<form class="border mt-5 border-secondary text-center p-3" method="post">
			{% csrf_token %}
		    <p class="h4 mb-4 text-secondary text-center" style="color: rgb(210, 216, 216); " >Sign up</p>

		    <!-- {{ form.as_p }} -->

			{% for field in form %}
		    <p>
	        	{{ field.label_tag }}
	        	{{ field }} 
		        <!-- {% if field.help_text %}
		          <small style="color: grey">{{ field.help_text }}</small>
		        {% endif %} -->
		        {% for error in field.errors %}
		          <p style="color: red">{{ error }}</p>
		        {% endfor %}
		    </p>
		    {% endfor %}

		    <!-- Sign up button -->
		    <button class="btn btn-secondary my-4 btn-block" type="submit">Sign up</button>

		    <!-- Social register -->
		   
			<div class="foot-lnk">
				<label for="tab-1"><a href="{% url 'login' %}">Already Member?</a></label>
			</div>

		   
		</form>
		<!-- Default form register -->
	</div>



</div>

{% block script %}
<script type="text/javascript">
	function get_ip(json) {
		$("#id_location").val(json.ip);
	}
</script>

<script src="https://api.ipify.org?format=jsonp&callback=get_ip"></script>
{% endblock %}

{% endblock %}