file_upload/urls.py
from django.urls import re_path, path
from . import views

# namespace
app_name = "file_upload"

urlpatterns = [

    # Upload File Without Using Model Form
    #re_path(r'^upload1/$', views.file_upload, name='file_upload'),

    # Upload Files Using Model Form
    re_path(r'^upload2/$', views.model_form_upload, name='model_form_upload'),

    # Upload Files Using Ajax Form
    re_path(r'^upload3/$', views.ajax_form_upload, name='ajax_form_upload'),

    # Handling Ajax requests
    re_path(r'^ajax_upload/$', views.ajax_upload, name='ajax_upload'),
    
    path('books/<int:pk>/', views.delete_book, name='delete_book'),


    # View File List 
    path('list', views.file_list, name='file_list'),  

]

users/urls.py
from django.urls import path

from .views import home_view, signup_view, dashboard_view,emailmsg,add_Code_view,auth,SignUpView

app_name = "users"

urlpatterns = [

    path('', home_view, name='home'),
   # path('signup/', signup_view, name='sign-up'),
    path('sign-up/', SignUpView.as_view(), name='sign-up'),

    path('dashboard/', dashboard_view, name='dashboard'),
    path('OTP/', auth, name='OTP'),
   # path('OTP/',add_Code_view.as_view(),name='OTP'),


   # path('OTP/', emailmsg("authentcations"," Your OTP is: ","ftcode2021@gmail.com"), name='OTP'),

    
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import  LogoutView
from users.views import LoginUser
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('profile/', include('profiles.urls', namespace='profiles')),
    path('file/', include("file_upload.urls")),
    path('file/', include("file_download.urls")),
]

urlpatterns += [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
 
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

file_upload/models.py
from django.db import models
import os
import uuid
from django.contrib.auth.models import User
from model_utils import Choices

# Create your models here.
# Define user directory path

class active(models.Model):
    user_name = models.CharField(max_length=255)
    
def user_directory_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = '{}.{}'.format(uuid.uuid4().hex[:10], ext)
    return os.path.join("files", filename)


class File(models.Model):
    file = models.FileField(upload_to=user_directory_path) 
    name = models.CharField(max_length=20, verbose_name="filename")
    sec_key = models.CharField(max_length=200)
    allow = models.ManyToManyField(User ,null=True)

    def delete(self, *args, **kwargs):
        self.file.delete()
        super().delete(*args, **kwargs)

file_upload/forms.py
from django import forms
from .models import File
from django.contrib.auth.models import User
from model_utils import Choices

DEMO_CHOICES =(
    ("1", "Naveen"),
    ("2", "Pranav"),
    ("3", "Isha"),
    ("4", "Saloni"),
)
# Regular form
class FileUploadForm(forms.Form):
    file = forms.FileField(widget=forms.ClearableFileInput(attrs={'class': 'form-control'}))
    name = forms.CharField(label="Upload Method", max_length=20,
                                    widget=forms.TextInput(attrs={'class': 'form-control'}))

    def clean_file(self):
        file = self.cleaned_data['file']
        ext = file.name.split('.')[-1].lower()
       
        return file


# Model form
class FileUploadModelForm(forms.ModelForm):
   
    class Meta:
        model = File
        fields = ('file', 'name','sec_key','allow')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'file': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'sec_key': forms.TextInput(attrs={'class': 'form-control'}),
        }

    def clean_file(self):
        file = self.cleaned_data['file']
        ext = file.name.split('.')[-1].lower()
       # return cleaned data is very important.
        return file

file_upload/views.py
from django.shortcuts import render, redirect
from .models import File
from .forms import FileUploadForm, FileUploadModelForm
import os
import uuid
from django.http import JsonResponse
from django.template.defaultfilters import filesizeformat
from cryptography.fernet import Fernet
from file_download.forms import BlogForm

# Create your views here.

def add_blog(request):
    if request.method == "POST":
        form = BlogForm(request.POST)
        if form.is_valid():
            blog_item = form.save(commit=False)
            blog_item.save()
            return redirect('file_upload:file_list')
    else:
        form = BlogForm()
    return render(request, 'file_upload/file_list.html', {'form': form})
     
# Show file list
def file_list(request):
    files = File.objects.all().order_by("-id")
    if request.method == "POST":
        form = BlogForm(request.POST)
        if form.is_valid():
            blog_item = form.save(commit=False)
            blog_item.save()
            return redirect('file_upload:file_list')
    else:
        form = BlogForm()
     
    return render(request, 'file_upload/file_list.html', {'files': files ,'form': form})


# Regular file upload without using ModelForm
def file_upload(request):
    if request.method == "POST":
        form = FileUploadForm(request.POST, request.FILES)
        if form.is_valid():
            # get cleaned data
            name = form.cleaned_data.get("name")
            raw_file = form.cleaned_data.get("file")
            new_file = File() 
            new_file.file = handle_uploaded_file(raw_file)
            new_file.name = name
            new_file.save()
            return redirect("file_upload:file_list")
    else:
        form = FileUploadForm()

    return render(request, 'file_upload/upload_form.html', {'form': form,
                                                            'heading': 'Upload files with Regular Form'})


def handle_uploaded_file(file):
    ext = file.name.split('.')[-1]
    file_name = '{}.{}'.format(uuid.uuid4().hex[:10], ext)
    # file path relative to 'media' folder
    file_path = os.path.join('files', file_name)
    absolute_file_path = os.path.join('media', 'files', file_name)

    directory = os.path.dirname(absolute_file_path)
    if not os.path.exists(directory):
        os.makedirs(directory)

    with open(absolute_file_path, 'wb+') as destination:
        for chunk in file.chunks():
            destination.write(chunk)

    return file_path


def write_key():
    """
    Generates a key and save it into a file
    """
    key = Fernet.generate_key()
    with open("key.key", "wb") as key_file:
        key_file.write(key)


def load_key():
    """
    Loads the key from the current directory named `key.key`
    """
    return open("key.key", "rb").read()





write_key()
key = load_key()

def delete_book(request, pk):
    if request.method == 'POST':
        book = File.objects.get(pk=pk)
        book.delete()
    return redirect('file_upload:file_list')




from .models import active
from django.contrib.auth.models import User

# Upload File with ModelForm
def model_form_upload(request):
    all_User = User.objects.all()
    if request.method == "POST":
        form = FileUploadModelForm(request.POST, request.FILES)
        if form.is_valid():
            key =b'15aabnx7m8ju6F7XKS_hhGeBKsI-xDzkWyV9Pyj3qU4='
            gg = key.decode()
            print(gg)
            #f = Fernet(key)
            sec_key = form.cleaned_data.get('sec_key')
            dd = str(sec_key)
            f = Fernet(sec_key)
            file = request.FILES.get("file").read()

            cen=f.encrypt(file)
            file = request.FILES.get("file").seek(0)
            file = request.FILES['file'].write(cen)
            print(key)
            form.save()
            return redirect("file_upload:file_list")
    else:
        form = FileUploadModelForm()

    return render(request, 'file_upload/upload_form.html', {'form': form,
                                                            'heading': 'Upload files with ModelForm','Active':all_User})

def upload_book(request):
   
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            key = load_key()
            secret_key = form.cleaned_data.get('secret_key')
            f = Fernet(key)
            
            #request.FILES['pdf']
            #pdf = form.cleaned_data.get('pdf')
            
            pdf = request.FILES.get("pdf").read()

            cen=f.encrypt(pdf)
            pdf = request.FILES.get("pdf").seek(0)

            
            
            
    
            pdf = request.FILES['pdf'].write(cen)
            print('kr------NN:-',key)
            

            form.save()
            return redirect('book_list')
    else:
        form = BookForm()
    return render(request, 'upload_book.html', {
        'form': form
    })




# Upload File with ModelForm
def ajax_form_upload(request):
    form = FileUploadModelForm()
    return render(request, 'file_upload/ajax_upload_form.html', {'form': form,
                                                            'heading': 'File Upload with AJAX'})


# handling AJAX requests
def ajax_upload(request):
    if request.method == "POST":
        # 1. Regular save method
        # name = request.POST.get("name")
        # raw_file = request.FILES.get("file")
        # new_file = File()
        # new_file.file = handle_uploaded_file(raw_file)
        # new_file.name = name
        # new_file.save()

        # 2. Use ModelForm als ok.
        form = FileUploadModelForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            # Obtain the latest file list
            files = File.objects.all().order_by('-id')
            data = []
            for file in files:
                data.append({
                    "url": file.file.url,
                    "size": filesizeformat(file.file.size),
                    "name": file.name,
                    })
            return JsonResponse(data, safe=False)
        else:
            data = {'error_msg': "Only jpg, pdf and xlsx files are allowed."}
            return JsonResponse(data)
    return JsonResponse({'error_msg': 'only POST method accpeted.'})

file_upload/templates/file_upload/ajax_upload_form.html
{% extends "file_upload/base.html" %}
{% block content %}

{% if heading %}
<h3>{{ heading }}</h3>
{% endif %}

<form action="" method="post" enctype="multipart/form-data" id="form">
    <ul class="errorlist"></ul>
    {% csrf_token %}
{{ form.as_p }}
 <input type="button" class="btn btn-info form-control" value="submit" id="btn" />
</form>
<table class="table table-striped" id="result">
</table>
{% endblock %}


{% block js %}
<script src=" https://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.cookie.min.js "></script>
<script>
var csrftoken = $.cookie('csrftoken');
function csrfSafeMethod(method) {
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}

$(document).ready(function(){
   $('#btn').click(function(e){
        e.preventDefault();
        // 构建FormData对象
        var form_data = new FormData();
        form_data.append('file', $('#id_file')[0].files[0]);
        form_data.append('name', $('#id_name').val());
        $.ajax({
        url: '/file/ajax_upload/',
        data: form_data,
        type: 'POST',
        dataType: 'json',
        // 告诉jQuery不要去处理发送的数据, 发送对象。
        processData : false,
        // 告诉jQuery不要去设置Content-Type请求头
        contentType : false,
        // 获取POST所需的csrftoken
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }},
        success: function (data) {
            if(data['error_msg']) {
                var content = '<li>Only jpg, pdf and xlsx files are allowed.</li>';
                $('ul.errorlist').html(content);
            }
            else
            {
            var content= '<thead><tr>' +
            '<th>Name and URL</th>' +
            '<th>Size</th>' +
            '<th>Upload Method</th>' +
            '</tr></thead><tbody>';

             $.each(data, function(i, item) {
                  content = content +
                  '<tr><td>' +
                  "<a href= ' " +
                  item['url'] +
                  " '> " +
                  item['url'] +
                  '</a></td><td>' +
                  item['size'] +
                  '</td><td>' +
                  item['name'] +
                   '</td><tr>'
                });
             content = content + "</tbody>";
             $('#result').html(content);
             }
           },
        });
   });
 });
  </script>
{% endblock %}

file_upload/templates/file_upload/base.html
{% load static %}

<html lang="en">
<head>
<title>{% block title %}Upload and Download{% endblock %} </title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<link rel="stylesheet" href="./style.css">

<script  src="./script.js"></script>

<link href="{% static 'style.css' %}" rel="stylesheet">
<script type="text/javascript" src="{% static 'script.js' %}"></script>


</head>

<body>
 <!-- Page content of course! -->

 {% block content %} {% endblock %}



<!-- Bootstrap core JavaScript
================================================== -->


{% block js %} {% endblock %}

</body>
</html>

file_upload/templates/file_upload/ddd.html
<form method="POST" action="">
    {% csrf_token %}
  
  
    
    <div class="field_wrapper">
  
  
 
      {{ form.sec_key }}
      
    </div>
    
    <input type="submit" value="Save">
  </form>
  

file_upload/templates/file_upload/file_list.html
{% extends "file_upload/base.html" %}

{% block content %}

{% if files %}
<table class="container" >
        <h2> <a href="/file/upload2/" class="btn btn-primary  " target="_blank"> Upload !</a></h2>
        
    <thead>
        <tr>
			<th><h1>Download File</h1></th>
			<th><h1>Filesize</h1></th>
			<th><h1>Filename</h1></th>
            <th><h1>Vew File</h1></th>
            <th><h1>Delete File</h1></th>
		</tr>
        
    </thead>

    <tbody>
    
    {% for file in files %}
    <tr>
        <!-- Option 1 <td><a href="{{ file.file.url }}/">{{ file.file.url }}</a></td> -->
        <td style="color: azure !important;"><a href="/file/download{{ file.file.url }}/">Download File</a></td>
        <td style="color: azure;">{{ file.file.size | filesizeformat }}</td>
        <td style="color: azure;">{{ file.name }}</td>
        <td style="color: azure;">
            <a href="{{file.file.url  }}" class="btn btn-primary btn-sm p" target="_blank">
              View File
            </a>
        </td>
        <td>
            <form method="post" action="{% url 'file_upload:delete_book' file.pk %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger btn-sm p">Delete</button>
            </form>
    </tr>
    {% endfor %}
    </tbody>
</table>

{% else %}
<h1><span class="blue">&lt;</span>Files List <span class="blue">&gt;</span> <span class="yellow"></pan></h1>
dddd

<h1><span class="blue">&lt;</span>No files uploaded yet. Please click <span class="blue">&gt;</span><a href="{% url 'file_upload:file_upload' %}">here</a> <span class="yellow">to upload files.</pan></h1>

{% endif %}

{% endblock %}

file_upload/templates/file_upload/upload_form.html
{% extends "file_upload/base.html" %}
{% block content %}

<div class="container">
  <h1><span class="blue">&lt;</span>Uploading file  <span class="blue">&gt;</span> <span class="yellow"></pan></h1>
<form action="" method="post" enctype="multipart/form-data" >
  {% csrf_token %}
  {{ form.as_p }}
 <button class="btn btn-info form-control " type="submit" value="submit">Upload</button>
</form>
</div>
{% endblock %}