users/urls.py
from django.urls import path

from .views import home_view, signup_view, dashboard_view,emailmsg,add_Code_view,auth,SignUpView

app_name = "users"

urlpatterns = [

    path('', home_view, name='home'),
   # path('signup/', signup_view, name='sign-up'),
    path('sign-up/', SignUpView.as_view(), name='sign-up'),

    path('dashboard/', dashboard_view, name='dashboard'),
    path('OTP/', auth, name='OTP'),
   # path('OTP/',add_Code_view.as_view(),name='OTP'),


   # path('OTP/', emailmsg("authentcations"," Your OTP is: ","ftcode2021@gmail.com"), name='OTP'),

    
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import  LogoutView
from users.views import LoginUser
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('profile/', include('profiles.urls', namespace='profiles')),
    path('file/', include("file_upload.urls")),
    path('file/', include("file_download.urls")),
]

urlpatterns += [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
 
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/navbar.html
<!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-dark secondary-color mb-5">

<div class="container">
    <!-- Navbar brand -->
    <a class="navbar-brand" href="{% url 'users:home' %}">Ciphered Storage</a>

    <!-- Collapse button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav" aria-controls="basicExampleNav"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Collapsible content -->
    <div class="collapse navbar-collapse" id="basicExampleNav">

        <!-- Links -->
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'users:home' %}">Home
                    <span class="sr-only">(current)</span>
                </a>
            </li>
            
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:sign-up' %}">Sign up</a>
            </li>
            
           

        </ul>
        <!-- Links -->

        <!-- login and logout buttons -->
        <div class="my-1 mr-3">
            {% if user.is_authenticated %}
                <a class="btn btn-outline-white btn-md my-2 my-sm-0 ml-3" href="{% url 'logout' %}">Logout</a>
        </div>
        <div class="my-1 mr-3">
                <!-- user icon -->
                <div class="white-text">
                   <i class="fa fa-user" aria-hidden="true"></i>
                   {{ request.user }}
                </div>
            {% else %}
                <a class="btn btn-outline-white btn-md my-2 my-sm-0 ml-3" href="{% url 'login' %}">Login</a>
            {% endif %}
        </div>        
    </div>
    <!-- Collapsible content -->

</div>

</nav>
<!--/.Navbar-->